---

    - name: ssh root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        insertafter: "^#PermitRootLogin"
        line: "PermitRootLogin yes"

    - name: ssh restart
      service:
        name: sshd
        state: restarted
