---

    - name: hosts Change
      template: src="roles/drbd9/templete/hosts"
                dest="/etc/hosts"

    - name: DRBD9 Repository Get
      apt_repository: repo='ppa:linbit/linbit-drbd9-stack'

    - name: Install Packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - drbd-utils
        - python-drbdmanage
        - drbd-dkms
        - lvm2

    - name: Lvm Create
      lvg:  vg=drbdpool pvs=/dev/sdc1

